version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SSD}/data/resilio-sync/downloads:/downloads
      - CHANGE_TO_COMPOSE_DATA_PATH/resilio-sync/sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resilio-sync.rule=Host(`resilio-sync.omv.kllnr.de`)"
      - "traefik.http.routers.resilio-sync.entrypoints=websecure"
      - "traefik.http.routers.resilio-sync.tls.certresolver=omv_certresolver"
    restart: unless-stopped