version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBPASSWORD=${PASSWD}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      external-vlan:
        ipv4_address: 192.168.7.241
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`pihole.omv.kllnr.de`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls.certresolver=omv_certresolver"
    restart: unless-stopped

networks:
  external-vlan:
    external: true
