version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
     - node.name=es01
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "data01:/usr/share/elasticsearch/data"
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kib01
    environment:
     - ELASTICSEARCH_HOSTS=http:es01:9200
    volumes:
      - "datakib01:/usr/share/kibana/data"
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - elastic

volumes:
  data01:
  datakib01:

networks:
  elastic:
    driver: bridge